# Generated by Django 4.1 on 2022-09-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_icon", models.CharField(max_length=30)),
                ("service_heading", models.CharField(max_length=30)),
                ("service_details", models.CharField(max_length=30)),
            ],
        ),
    ]
