# Generated by Django 4.1 on 2022-09-22 13:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_heading',
            field=tinymce.models.HTMLField(),
        ),
    ]
