# Generated by Django 4.1 on 2022-09-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0002_alter_service_service_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_heading",
            field=models.CharField(max_length=30),
        ),
    ]
